// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHEfH9uDIci1bBFEgjOpyVjzcjAAQ3LcE',
    appId: '1:366672467171:web:f6b9f3a88349414168e1d6',
    messagingSenderId: '366672467171',
    projectId: 'auth-ffbd3',
    authDomain: 'auth-ffbd3.firebaseapp.com',
    storageBucket: 'auth-ffbd3.appspot.com',
    measurementId: 'G-JL3B1D0CNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVBhuSwyyj_R9T7RxpqAPfUheXk66snzI',
    appId: '1:366672467171:android:672aeef32cbe37de68e1d6',
    messagingSenderId: '366672467171',
    projectId: 'auth-ffbd3',
    storageBucket: 'auth-ffbd3.appspot.com',
  );
}
